name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Сначала проверим простые тесты
    - name: Run simple tests
      run: |
        python -c "def test(): assert 1+1==2; test(); print('Simple test passed')"
    
    # Потом попробуем импорт
    - name: Test imports
      run: |
        python -c "import sys; sys.path.append('src'); from calculator import add; print('Import successful!')"
    
    # И только потом запустим pytest
    - name: Run tests with HTML report
      run: |
        python -m pytest tests/ --html=report.html --self-contained-html -v
    
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
        retention-days: 30
